#!/bin/bash


if [[ "$1" == '.' ]]; then
	cat \
		<(find . -type f -name  "*.png" -printf "%T+\t%p\n") \
		<(find . -type f -name  "*.jpeg" -printf "%T+\t%p\n") | \
		sort -n | grep -v '.Rproj.user'
else
	cat \
	<(find ~/Dropbox/vimwiki -type f -name  "*.png" -printf "%T+\t%p\n" -or -name "*.Rmd" -printf "%T+\t%p\n") \
	<(find ~/prj -type f -name  "*.png" -printf "%T+\t%p\n") \
	<(find ~/prj -type f -name  "*.jpeg" -printf "%T+\t%p\n") | \
	sort -n | \
	tail -20

fi

