#!/bin/bash



cat \
<(find ~/Dropbox/vimwiki -type f -name  "*.md" -printf "%T+\t%p\n" -or -name "*.Rmd" -printf "%T+\t%p\n") \
<(find ~/prj -type f -name  "*.md" -printf "%T+\t%p\n") \
<(find ~/prj -type f -name  "*.Rmd" -printf "%T+\t%p\n") | \
sort -n | \
tail -20
