#!/usr/bin/env bash

set -ux


URL=$(git remote get-url origin)


if [[ $URL == *git@* ]]; then
    echo "Already git Url "
    exit 0
fi

if [[ $URL == *https:* ]]; then
    URL=$(echo $URL | sed 's|https://|git@|')
    URL=$(echo $URL | sed 's|/|:|')

    git remote set-url origin $URL
    exit 0
fi





