#!/bin/bash


set -eux

if [[ ! -d $PWD/.git ]]; then
    echo ".git not present. Intializing with git init"
    git init
fi

git config --local user.email "grepinsight@gmail.com"
git config --local user.name  "Albert Lee"
git config --local hub.host "https://github.com"
git config --local github.user "grepinsight"

GIT_PERSONAL="$(git config --local remote.origin.url | sed 's/github.com/github-personal.com/')"
git config --local remote.origin.url $GIT_PERSONAL


if [[ -n $GITHUB_PERSONAL_INFO_PATH ]]; then
	touch .envrc
	cat $GITHUB_PERSONAL_INFO_PATH >> .envrc
fi
