#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
git rebase -i origin/${BRANCH_NAME} 2> /dev/null

if [[ $? != 0 ]]; then
	num_commits=$(git log --oneline | wc -l)
	num_commits=$((num_commits - 1))

	git rebase -i HEAD~$num_commits
fi


