#!/bin/bash

git add .gitignore


number_of_staged_files=$(git status -s | grep -v '??' | wc -l)

if [[ $number_of_staged_files -eq 1 ]]; then
	git commit -m 'Update .gitignore'
else
	echo "[Error] There are more than one file on the stage"
fi

