#!/bin/bash


preview_func() {
    PASSED=$1
    if [[ -d $PASSED ]]; then
        echo "$PASSED is a directory"
        tree -L 2 $1
    elif [[ -f $PASSED ]]; then
        echo "$PASSED is a file"
        head -100 $1
    else
        echo "$PASSED is not valid"
        exit 1
    fi
}

export -f preview_func

git status -s | grep ?? | awk '{print $2}' | xargs ls -thord | awk '{print $8}' | tail -r |  fzf --reverse --preview "preview_func {}" --color light --margin 5,20 -m
