#!/bin/bash

#cat ~/.bash_eternal_history  | fzf | gcut -c1-49 --complement
# requires rpbcopy

option="/bin/cat" # default option, doing nothing
TODAY=$(date "+%Y-%m-%d")


if command -v gdate > /dev/null; then
	YESTERDAY=$(gdate -d "$TODAY -1 day" "+%Y-%m-%d")
else
	YESTERDAY=$(date -d "$TODAY -1 day" "+%Y-%m-%d")
fi

nofzf=0
while true; do
	#statements
	case "$1" in
		--today) option="$option | grep $TODAY"; shift ;;
		--yesterday) option="$option | grep $YESTERDAY"; shift ;;
		--here) option="$option | grep $PWD"; shift ;;
		--directory) cat ~/.bash_eternal_history | grep -w $TODAY | cut -f2 -d@ | cut -f1 -d "|" | strip.pl | uniq | awk '!x[$0]++' | grep prj; exit;;
		--nofzf) nofzf=1; shift ;;
		*) break;
	esac
done

postprocess() {
	perl -ne 'm/\d{10}\s*(.*)$/; print $1."\n"'  | \
	LC_ALL=C sort | \
	uniq | \
	fzf
}

if [ -z $ETERNAL_HISTORY_FILE ]; then
    if [ -n $ZSH_VERSION ]; then
        ETERNAL_HISTORY_FILE="~/.zsh_eternal_history"
    else
        # assume it's bash
        ETERNAL_HISTORY_FILE="~/.bash_eternal_history"
    fi
fi


if [[ $nofzf == 1 ]]; then
	search_result="cat $ETERNAL_HISTORY_FILE  | $option"
	res=$(eval $search_result)
else
	search_result="cat $ETERNAL_HISTORY_FILE  | $option | postprocess"
	res=$(eval $search_result)
fi
echo $res




if [[ $nofzf == 0 ]]; then
	echo "$res" | tr -d '\n' | rpbcopy
fi

