#!/bin/bash

#cat ~/.bash_eternal_history  | fzf | gcut -c1-49 --complement


option="cat" # default option, doing nothing
TODAY=$(date "+%Y-%m-%d")
YESTERDAY=$(gdate -d "$TODAY -1 day" "+%Y-%m-%d")
nofzf=0
while true; do
	#statements
	case "$1" in
		--today) option="$option | grep $TODAY"; shift ;;
		--yesterday) option="$option | grep $YESTERDAY"; shift ;;
		--here) option="$option | grep $PWD"; shift ;;
		--nofzf) nofzf=1; shift ;;
		*) break;
	esac
done

postprocess() {
	perl -ne 'm/\d{10}\s*(.*)$/; print $1."\n"'  | \
	LC_ALL=C sort | \
	uniq | \
	fzf
}

if [[ $nofzf == 1 ]]; then
	search_result="cat ~/.bash_eternal_history  | $option"
	res=$(eval $search_result)
else
	search_result="cat ~/.bash_eternal_history  | $option | postprocess"
	res=$(eval $search_result)
fi
echo $res




if [[ $nofzf == 0 ]]; then
	echo "$res" | tr -d '\n' | pbcopy
fi

