#!/bin/bash

paper="$(fd ".pdf$" ~/Dropbox/Papers/ \
    | fzf -e \
     --preview-window up:60% \
	 --preview "pdftotext -f 1 -l 3 '{1}' - ")"

if [[ -n "$paper" ]]; then
     open -a "PDF Expert" "$paper"
fi
