#!/bin/bash


SEARCHER="rg"

which $SEARCHER 2>/dev/null 1>&2 || SEARCHER="ag"
which $SEARCHER 2>/dev/null 1>&2 || SEARCHER="grep"



if [[ -z $1 ]]; then
    echo "Usage: "
    echo ""
    echo "    $(basename $0) <alias>"
    exit 1

fi
case $SEARCHER in
    rg) rg --no-ignore -w "alias $1" $HOME/.dotfiles;;
    ag) ag --no-ignore -w "alias $1" $HOME/.dotfiles;;
    *) grep -w "alias $1" $HOME/.dotfiles ;;
esac


