#!/bin/bash

echo "--- Agenda ---"
gcalcli-agenda-today

echo "--- QUESTIONS ---"
todoist list  | grep @question

rg -i question -l ~/vimwiki

echo "--- JIRA ---"
jira mine

echo "--- TODOIST ---"
todoist sync && todoist list | egrep -v "recurring|NiceToHave|Insighty-Life|Home|morning_routine|family"

echo "--- Git Summaries"
git summaries

