#!/bin/bash

FILE_TO_FD=$(basename $1)
NUMBER_OF_FILES_FOUND=$(fd $FILE_TO_FD | wc -l)
if [[ $NUMBER_OF_FILES_FOUND -gt 1 ]] ;then
	file_to_inspect=$(fd $FILE_TO_FD | fzf | strip_color)
else
	file_to_inspect=$(fd $FILE_TO_FD | strip_color)
fi

vim $file_to_inspect
