#!/bin/bash

ttys_result=$(find_ttys $HOME/Dropbox/vimwiki/diary/.questions.swp)

if [[ ! -z $ttys_result ]]; then

	session_name=$(tmux list-panes -a -F '#{session_name}:#{window_index}.#{pane_index} #{pane_tty}' | grep $ttys_result | awk '{print $1}')

	tmux switch -t $session_name
else
	vim $HOME/Dropbox/vimwiki/questions.md
fi
