#!/usr/bin/env bash


set -x
CURRENT_DX_PROJECT=$(dx-project-pwd)
DX_WORKFLOW_DESTINATION_DIR="${CURRENT_DX_PROJECT}:/workflows"

java -jar ~/src/cromwell/dxWDL-v1.44.jar \
    compile \
    "$@" \
    -project "$CURRENT_DX_PROJECT" \
    -destination "$DX_WORKFLOW_DESTINATION_DIR" \
    -archive
